export const LOCAL_STORAGE_CART_KEY = "zd_free_cart_v3";
export const LEGACY_LOCAL_STORAGE_CART_KEYS = ["zd_free_cart_v1", "zd_free_cart_v2"] as const;
export const SESSION_CART_NOTICE_KEY = "zd_free_cart_notice_v1";
export const MAX_CART_STORAGE_BYTES = 8192;
export const MAX_CART_ITEM_COUNT = 30;
export const SESSION_ORDER_KEY = "zd_free_last_order_v1";
export const DEFAULT_SITE_URL = "https://zeydesign.online";
export const DEFAULT_SUPABASE_URL = "https://koxfmngebugdkfzvnphp.supabase.co";
export const DEFAULT_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_n7M8G8Jl5gurGMN1gr1sDg_sWM6X6cL";
